#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern C {
#endif

extern uint32_t _binary_sega_dreamcast_holly_TAVertexParameter_polygon_type_10_class_start __asm("_binary_sega_dreamcast_holly_TAVertexParameter_polygon_type_10_class_start");
extern uint32_t _binary_sega_dreamcast_holly_TAVertexParameter_polygon_type_10_class_end __asm("_binary_sega_dreamcast_holly_TAVertexParameter_polygon_type_10_class_end");
extern uint32_t _binary_sega_dreamcast_holly_TAVertexParameter_polygon_type_10_class_size __asm("_binary_sega_dreamcast_holly_TAVertexParameter_polygon_type_10_class_size");

#ifdef __cplusplus
}
#endif
