CLASS_PATH = \
	example/DreamcastVideo2.class.o \
	example/DreamcastVideo.class.o \
	java/io/PrintStream.class.o \
	java/lang/DecimalDigits.class.o \
	java/lang/Double.class.o \
	java/lang/Float.class.o \
	java/lang/Integer.class.o \
	java/lang/Long.class.o \
	java/lang/Math.class.o \
	java/lang/Object.class.o \
	java/lang/String.class.o \
	java/lang/System.class.o \
	java/misc/Memory.class.o \
	java/misc/Resource.class.o \
	model/FacePTN.class.o \
	model/ModelObject.class.o \
	model/UntitledModel.class.o \
	model/Vec2.class.o \
	model/Vec3.class.o \
	sega/dreamcast/holly/Background.class.o \
	sega/dreamcast/holly/CoreBits.class.o \
	sega/dreamcast/holly/Core.class.o \
	sega/dreamcast/holly/Holly.class.o \
	sega/dreamcast/holly/ISPTSP.class.o \
	sega/dreamcast/holly/RegionArray.class.o \
	sega/dreamcast/holly/RegionArray_OPBSize.class.o \
	sega/dreamcast/holly/TABits.class.o \
	sega/dreamcast/holly/TAFIFOPolygonConverter.class.o \
	sega/dreamcast/holly/TAGlobalParameter.class.o \
	sega/dreamcast/holly/TAGlobalParameter_end_of_list.class.o \
	sega/dreamcast/holly/TAGlobalParameter_modifier_volume.class.o \
	sega/dreamcast/holly/TAGlobalParameter_object_list_set.class.o \
	sega/dreamcast/holly/TAGlobalParameter_polygon_type_0.class.o \
	sega/dreamcast/holly/TAGlobalParameter_polygon_type_1.class.o \
	sega/dreamcast/holly/TAGlobalParameter_polygon_type_2.class.o \
	sega/dreamcast/holly/TAGlobalParameter_polygon_type_3.class.o \
	sega/dreamcast/holly/TAGlobalParameter_polygon_type_4.class.o \
	sega/dreamcast/holly/TAGlobalParameter_sprite.class.o \
	sega/dreamcast/holly/TAGlobalParameter_user_tile_clip.class.o \
	sega/dreamcast/holly/TAParameter.class.o \
	sega/dreamcast/holly/TAVertexParameter.class.o \
	sega/dreamcast/holly/TAVertexParameter_modifier_volume.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_0.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_10.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_11.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_12.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_13.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_14.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_1.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_2.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_3.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_4.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_5.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_6.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_7.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_8.class.o \
	sega/dreamcast/holly/TAVertexParameter_polygon_type_9.class.o \
	sega/dreamcast/holly/TAVertexParameter_sprite_type_0.class.o \
	sega/dreamcast/holly/TAVertexParameter_sprite_type_1.class.o \
	sega/dreamcast/holly/TextureMemoryAllocation.class.o \
	sega/dreamcast/MemoryMap.class.o \
	sega/dreamcast/systembus/SystembusBits.class.o \
	sega/dreamcast/systembus/Systembus.class.o
