CLASS_PATH = \
	classes/example/GdromClassLoader.class.o \
	classes/example/GdromDirectoryRecordHandler.class.o \
	classes/filesystem/iso9660/ByteParser.class.o \
	classes/filesystem/iso9660/DirectoryRecord.class.o \
	classes/filesystem/iso9660/ExtentReader.class.o \
	classes/filesystem/iso9660/PrimaryVolumeDescriptor.class.o \
	classes/filesystem/iso9660/VolumeParser.class.o \
	classes/java/io/PrintStream.class.o \
	classes/java/lang/DecimalDigits.class.o \
	classes/java/lang/Integer.class.o \
	classes/java/lang/Float.class.o \
	classes/java/lang/Number.class.o \
	classes/java/lang/Object.class.o \
	classes/java/lang/String.class.o \
	classes/java/lang/System.class.o \
	classes/java/lang/Exception.class.o \
	classes/java/lang/Throwable.class.o \
	classes/java/lang/Backtrace.class.o \
	classes/sega/dreamcast/gdrom/G1IF.class.o \
	classes/sega/dreamcast/gdrom/GdromIF.class.o \
	classes/sega/dreamcast/gdrom/GdromBits.class.o \
	classes/sega/dreamcast/gdrom/Gdrom.class.o \
	classes/sega/dreamcast/gdrom/GdromExtentReader.class.o \
	classes/sega/dreamcast/gdrom/GdromCommandPacketFormat_cd_read.class.o \
	classes/sega/dreamcast/gdrom/GdromCommandPacketFormat.class.o \
	classes/sega/dreamcast/gdrom/GdromCommandPacketFormat_get_toc.class.o \
	classes/sega/dreamcast/gdrom/GdromCommandPacketInterface.class.o \
	classes/sega/dreamcast/gdrom/GdromProtocol.class.o \
	classes/jvm/internal/Loader.class.o \
	classes/jvm/internal/Memory.class.o \
	classes/java/io/IOException.class.o \
	classes/java/nio/BufferUnderflowException.class.o \
	classes/java/nio/BufferOverflowException.class.o \
	classes/java/lang/IllegalStateException.class.o \
	classes/java/lang/UnsupportedOperationException.class.o \
	classes/java/lang/IllegalAccessException.class.o \
	classes/java/lang/IllegalArgumentException.class.o \
	classes/java/lang/SecurityException.class.o \
	classes/java/lang/InterruptedException.class.o \
	classes/java/lang/ArrayStoreException.class.o \
	classes/java/lang/IndexOutOfBoundsException.class.o \
	classes/java/lang/CloneNotSupportedException.class.o \
	classes/java/lang/ArithmeticException.class.o \
	classes/java/lang/StringIndexOutOfBoundsException.class.o \
	classes/java/lang/NegativeArraySizeException.class.o \
	classes/java/lang/RuntimeException.class.o \
	classes/java/lang/NullPointerException.class.o \
	classes/java/lang/NumberFormatException.class.o \
	classes/java/lang/ArrayIndexOutOfBoundsException.class.o \
	classes/java/lang/IllegalMonitorStateException.class.o \
	classes/java/lang/InstantiationException.class.o \
	classes/java/lang/Exception.class.o \
	classes/java/lang/IllegalThreadStateException.class.o \
	classes/java/lang/ClassCastException.class.o \
	classes/java/lang/ClassNotFoundException.class.o \
	classes/Main.class.o \
	classes/example/JavaCube.class.o \
	classes/example/JavaCubeDirectoryRecordHandler.class.o \
	classes/java/lang/Math.class.o \
	classes/java/nio/ByteBuffer.class.o \
	classes/java/nio/Buffer.class.o \
	classes/jvm/internal/SH4Intrinsic.class.o \
	classes/model/FacePTN.class.o \
	classes/model/ModelObject.class.o \
	classes/model/CubeModel.class.o \
	classes/model/Vec2.class.o \
	classes/model/Vec3.class.o \
	classes/sega/dreamcast/holly/Background.class.o \
	classes/sega/dreamcast/holly/Core.class.o \
	classes/sega/dreamcast/holly/CoreBits.class.o \
	classes/sega/dreamcast/holly/VideoOutput.class.o \
	classes/sega/dreamcast/holly/VideoOutputMode.class.o \
	classes/sega/dreamcast/holly/ISPTSP.class.o \
	classes/sega/dreamcast/holly/RegionArray.class.o \
	classes/sega/dreamcast/holly/RegionArray_OPBSize.class.o \
	classes/sega/dreamcast/holly/TABits.class.o \
	classes/sega/dreamcast/holly/TAFIFOPolygonConverter.class.o \
	classes/sega/dreamcast/holly/TAGlobalParameter.class.o \
	classes/sega/dreamcast/holly/TAVertexParameter.class.o \
	classes/sega/dreamcast/holly/TextureMemoryAllocation.class.o \
	classes/sega/dreamcast/sh7091/StoreQueueBuffer.class.o
